refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S%.3f)} {level} [{thread}] {target} - {m}{n}"
  requests:
    kind: rolling_file
    path: "/data/rlink/log/job.log"
    append: true
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S%.3f)} {level} [{thread}] {target} - {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 50 mb
      roller:
        kind: fixed_window
        pattern: '/data/rlink/log/job.log.{}'
        base: 1
        count: 5

root:
  level: info
  appenders:
    - requests
